<a href="https://colab.research.google.com/github/sukhdhillion321-web/notes/blob/main/libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [ ]:
s= np.array([1,2,3,4,5])
print(s)

[1 2 3 4 5]


In [ ]:
type(s)

numpy.ndarray

In [ ]:
s=np.array([[1,2,3],[1,4,5]])
print(s)

[[1 2 3]
 [1 4 5]]


In [ ]:
s=np.array([[[1,2,3],[1,3,5],[5,6,7]]])
print(s)

[[[1 2 3]
  [1 3 5]
  [5 6 7]]]


In [ ]:
h=np.array([1,2,3,6],dtype=float)
print(h)

[1. 2. 3. 6.]


In [ ]:
h=np.array([1,2,3],dtype=bool)
print(h)

[ True  True  True]


In [ ]:
h=np.array([3,5,6],dtype=complex)
print(h)

[3.+0.j 5.+0.j 6.+0.j]


In [ ]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((4))

array([1., 1., 1., 1.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((4,3))

array([[0.13266099, 0.5748804 , 0.28070406],
       [0.69818716, 0.15128227, 0.35814851],
       [0.30257384, 0.01348734, 0.10542238],
       [0.26112945, 0.60988064, 0.70302362]])

In [ ]:
np.random.random((4))

array([0.90958509, 0.95968667, 0.21513328, 0.36727626])

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.linspace(-3,10,6)

array([-3. , -0.4,  2.2,  4.8,  7.4, 10. ])

In [ ]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a1=np.array([1,2,3]) #one dimensional array
a1

array([1, 2, 3])

In [ ]:
a2=np.arange(12,dtype=float).reshape(3,4) #matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3=np.arange(8).reshape(2,2,2) #3d----tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])