<a href="https://colab.research.google.com/github/sukhdhillion321-web/notes/blob/main/practice_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([10,20,30,40,50])    #1D array

array([10, 20, 30, 40, 50])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#shape,size and datatype

In [9]:
s1=np.arange(10)    #1D
s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
s2=np.arange(12).reshape(3,4)  #2D
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
s3=np.arange(8).reshape(2,2,2)     #3d
s3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
s1.shape

(10,)

In [15]:
s2.shape

(3, 4)

In [16]:
s3.shape

(2, 2, 2)

In [17]:
s1.size

10

In [18]:
s2.size

12

In [19]:
s3.size

8

In [20]:
print(s1.dtype)
print(s2.dtype)
print(s3.dtype)

int64
int64
int64


In [21]:
h1=np.array([5,15,25,35,45])
h1

array([ 5, 15, 25, 35, 45])

In [22]:
h1[3]

np.int64(35)

In [24]:
h2=np.arange(16).reshape((4,4))
h2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
h2[2:3]

array([[ 8,  9, 10, 11]])

In [26]:
t1=np.array([10,20,30,40,50])
t1

array([10, 20, 30, 40, 50])

In [27]:
t1[2:5]

array([30, 40, 50])

In [28]:
t2=np.arange(12).reshape((3,4))
t2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
t2[2:3]

array([[ 8,  9, 10, 11]])

In [30]:
r1=np.arange(12).reshape((3,4))
r1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
r1+5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
np.sum(r1)

np.int64(66)

In [33]:
np.max(r1)

np.int64(11)

In [34]:
np.min(r1)

np.int64(0)

In [35]:
np.mean(r1)

np.float64(5.5)

In [37]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a.reshape((12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a[2:3]

array([[ 8,  9, 10, 11]])

In [ ]:
a.reshape((12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
s=np.array([10,40,50,60,80])
s


array([10, 40, 50, 60, 80])

In [46]:
s[0:3]

array([10, 40, 50])

In [47]:
b=np.arange(16).reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
b[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
d=np.array([10,50,30,20])
c=np.array([20,10,30,20])
d+c

array([30, 60, 60, 40])

In [54]:
d*5

array([ 50, 250, 150, 100])

In [55]:
np.max(d)

np.int64(50)

In [56]:
np.min(d)

np.int64(10)

In [57]:
np.mean(d)

np.float64(27.5)